export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const SIGN_START = "SIGN_START";
export const SIGN_SUCCESS = "SIGN_SUCCESS";
export const SIGN_FAILED = "SIGN_FAILED";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_CONNECT_FAILED = "SOCKET_CONNECT_FAILED";
export const SOCKET_CONNECT_SUCCESS = "SOCKET_CONNECT_SUCCESS";

export const CONVERSATION_LOAD_SUCCESS = "CONVERSATION_LOAD_SUCCESS";
export const CONVERSATION_LOAD_START = "CONVERSATION_LOAD_START";
export const CONVERSATION_LOAD_FAILED = "CONVERSATION_LOAD_FAILED";
