export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const SIGN_START = "SIGN_START";
export const SIGN_SUCCESS = "SIGN_SUCCESS";
export const SIGN_FAILED = "SIGN_FAILED";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
